<?php if ($_item = $this->getItem()): ?>
<table cellspacing="0" class="qty-table">
    <tr>
        <td><?php echo Mage::helper('sales')->__('Ordered') ?></td>
        <td><strong><?php echo $_item->getQtyOrdered()*1 ?></strong></td>
    </tr>
    <?php if ((float) $_item->getQtyInvoiced()): ?>
    <tr>
        <td><?php echo Mage::helper('sales')->__('Invoiced') ?></td>
        <td><strong><?php echo $_item->getQtyInvoiced()*1 ?></strong></td>
    </tr>
    <?php endif; ?>
    <?php if ((float) $_item->getQtyShipped()): ?>
    <tr>
        <td><?php echo Mage::helper('sales')->__('Shipped') ?></td>
        <td><strong><?php echo $_item->getQtyShipped()*1 ?></strong></td>
    </tr>
    <?php endif; ?>
    <?php if ((float) $_item->getQtyRefunded()): ?>
    <tr>
        <td><?php echo Mage::helper('sales')->__('Refunded') ?></td>
        <td><strong><?php echo $_item->getQtyRefunded()*1 ?></strong></td>
    </tr>
    <?php endif; ?>
    <?php if ((float) $_item->getQtyCanceled()): ?>
    <tr>
        <td><?php echo Mage::helper('sales')->__('Canceled') ?></td>
        <td><strong><?php echo $_item->getQtyCanceled()*1 ?></strong></td>
    </tr>
    <?php endif; ?>
    <?php // GET AVAILABLE STOCK QTY (below) ?>
    <tr style="background:#daeae2!important;">
        <?php 
            $_sku = $this->escapeHtml($this->getSku());
            $_products = Mage::getModel('catalog/product')->loadByAttribute('sku', $_sku);
            $_stocks = Mage::getModel('cataloginventory/stock_item')->loadByProduct($_products)->getQty();
        ?>
        <td><?php echo Mage::helper('sales')->__('Stock') ?></td>
        <td><strong><?php echo intval($_stocks) ?></strong></td>
     </tr>
    <?php // End ?>
</table>
<?php endif; ?>
